### PR TITLE
add support for external data sources

### PR DESCRIPTION
**Pull request by Geoffrey-D**
Hello,

This PR triggers the following events when items are dropped from an external source:
 -   @node-drop-ext
 -   @node-over-ext
 -   @node-dragenter-ext
 -   @node-dragleave-ext

Would it be possible to create a new npm version once this PR is merged?

Thx!

### CODE REVIEW

**Comment by N00ts** [comment]
Hey this is cool idea, I think it could be more consistent if there is no "ext" in event name and everything goes in same event. The "external" nature could be handled by sending an object like:

`{
 external: boolean,
 dataTransfer,
 node
}`

Also in your PR, events seems to be fired twice (drop can emit "drop" and "dropext")

What do you think ?

**Comment by Geoffrey-D** [comment]
> Hey this is cool idea, I think it could be more consistent if there is no "ext" in event name and everything goes in same event. The "external" nature could be handled by sending an object like:
> 
> `{ external: boolean, dataTransfer, node }`
> 
> Also in your PR, events seems to be fired twice (drop can emit "drop" and "dropext")
> 
> What do you think ?

Excellent idea, I didn't know if I could alter the standard events.

I made the changes, I let you check if it fits your idea :)

**Comment by N00ts** [comment]
Looks really good ! Can you update documentation ?

**Comment by Geoffrey-D** [comment]
Done! I also always added the "evt, external & dataTransfer" data to be more consistent

**Comment by Geoffrey-D** [comment]
Is everything OK with this PR? can it be merged?

**Comment by N00ts** [comment]
Seems that tests are broken can you repair it ? ^^

**Comment by Geoffrey-D** [comment]
Sorry about that, fixed

**Pull request merged**
